# Generated by Django 3.0.4 on 2020-03-11 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_auto_20200311_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blood_groups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('display', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Names',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('use', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=30)),
                ('family', models.CharField(max_length=30)),
                ('given', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('PatientId', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('Other', 'Other')], max_length=10)),
                ('MaritalStatus', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Window(er)', 'Window(er)'), ('Nan', 'None')], max_length=10)),
                ('birthdate', models.DateField()),
                ('Blood_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.Blood_groups')),
                ('PatientName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoapp.Names')),
            ],
        ),
    ]
