# Generated by Django 3.0.4 on 2020-03-11 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_auto_20200311_1214'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blood_groups',
            new_name='Blood_group',
        ),
        migrations.RenameModel(
            old_name='Names',
            new_name='Name',
        ),
    ]
