# Generated by Django 3.0.4 on 2020-03-11 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0004_auto_20200311_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='birthdate',
            new_name='birthday',
        ),
    ]
